---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: Enhancement
assignees: ''

---

# Please delete all instructional lines and parts (marked with ❗ and including this heading) before submitting.
- Before submitting an issue, look at the [project goals](https://github.com/Windows200000/TwitchDropsMiner-updated#project-goals) !!! (❗Delete this part before submitting)
- If your issue is specific to one Operating System, consider whether it should be a bug report instead. (❗Delete this line before submitting)

## Problem being addressed:
Is your feature request related to a problem? If so, provide a clear and concise description of what the problem is. (❗Delete this line before submitting)
e.g. I'm always frustrated when [...] (❗Delete this line before submitting)

## Proposed solution:
A clear and concise description of what you want to happen. (❗Delete this line before submitting)

## Alternative:
A clear and concise description of any alternative solutions or features you've considered. (❗Delete this line before submitting)

## Additional context
Add any other context or screenshots about the feature request here. (❗Delete this line before submitting)
