name: Feature request
description: Suggest an idea for TDM.
labels: ["Enhancement"]
body:


  - type: markdown
    attributes:
      value: |
        ## Before submitting an issue, look at the [project goals](https://github.com/Windows200000/TwitchDropsMiner-updated#project-goals)!
        If your issue is specific to one Operating System, consider whether it should be a bug report instead.
        Create only **one issue per feature**. This ensures no feature is forgotten.

        ### Bad Title:
        - 32-bit     | What do you actually want?
        - Status Icon in the tray     | What should it do?
        - Received error (working fine prior to reboot)
        - I am getting an error when trying to run

        ### Good Title:
        - Create a build for 32-bit Windows
        - Exclude impossible campaigns
        - TypeError: 'NoneType' object is not subscriptable
        - Drops not being claimed in the intended way, causing some to be missed and no notifications

  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a problem? If so, provide a clear and concise description of what the problem is.
      placeholder: When I have many Windows open, it can take a while to find TDM.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Solution(s)
      description: What do you want to happen/change.
      placeholder: Don't hide tray icon when TDM Window is open.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional notes
      description: Add any other context, ideas or screenshots about the feature request here.
      placeholder: Maybe, there should be an option to hide/show it.
    validations:
      required: false
